version: "3.7"

services:

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

  database:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example